USE choonsik; 

DROP TABLE IF EXISTS TBL_BOARD;
DROP TABLE IF EXISTS TBL_MEMBER;

CREATE TABLE TBL_MEMBER
(
    MEMBER_CODE INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '멤버 번호',
    MEMBER_ID VARCHAR(50) NOT NULL UNIQUE COMMENT '멤버 아이디',
    MEMBER_PASSWORD VARCHAR(500) NOT NULL COMMENT '멤버 비밀번호',
    MEMBER_NAME VARCHAR(50) NOT NULL COMMENT '멤버 이름',
    MEMBER_ROLE VARCHAR(10) DEFAULT 'ROLE_USER' NOT NULL COMMENT '멤버 역할',
    MEMBER_STATUS CHAR(1) DEFAULT 'Y' NOT NULL COMMENT '멤버 활성 상태',
    MEMBER_EMAIL VARCHAR(100) NOT NULL COMMENT '멤버 이메일'
--     REG_DATE DATETIME DEFAULT NOW() NOT NULL COMMENT '가입일'
);
CREATE TABLE TBL_BOARD
(
    BOARD_CODE INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '게시글 번호',
    BOARD_TITLE TINYTEXT NOT NULL COMMENT '게시글 제목', 
    MEMBER_ID VARCHAR(50) NOT NULL COMMENT '멤버 아이디',
    IMG_URL TINYTEXT NOT NULL COMMENT '이미지 경로', -- DEFAULT로 사진 주자 
    REG_DATE DATETIME DEFAULT NOW() COMMENT '등록일',
    BOARD_STATUS CHAR(1) DEFAULT 'Y' COMMENT '게시글 활성 상태',
    FOREIGN KEY (MEMBER_ID) REFERENCES TBL_MEMBER (MEMBER_ID)
);